global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml
  - rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

scrape_configs:
  - job_name: mqtt
    file_sd_configs:
      - files:
          - 'mqtt.json'
