version: '3'
services:
  prometheus:
    networks:
      - traefik
    container_name: prometheus
    image: prom/prometheus:v2.50.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/gbb/prometheus:/etc/prometheus
      - /home/gbb/prometheus/prometheus-data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
networks:
  traefik:
    external: true