http:
  routers:
    broker:
      rule: ( Host(`globalbroker.mydomain.org`) && Path(`/mqtt`) )
      service: broker-srv
      entryPoints:
        - websecure
      tls: {}

  services:
    broker-srv:
      loadBalancer:
        servers:
          - url: "http://wbroker02:8083"

tcp:
  routers:
    mqtt:
      rule: HostSNI(`globalbroker.mydomain.org`,`wbroker02`)
      service: mqtt-srv
      entryPoints:
        - mqtts
      tls: {}

  services:
    mqtt-srv:
      loadBalancer:
        servers:
          - address: "wbroker02:1883"
