services:
  emqx:
    image: emqx:5.5.0
    container_name: emqx
    extra_hosts:
      - wbroker01:192.168.0.1
      - wbroker02:192.168.0.2
      - wbroker03:192.168.0.3
    environment:
      - "EMQX_NODE_NAME=emqx@wbroker03"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@wbroker01,emqx@wbroker02]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    network_mode: host
    restart: always
    volumes:
      - /home/gb/emqx:/opt/emqx/data
