services:
  emqx:
    image: emqx:5.5.0
    container_name: emqx
    environment:
      - "EMQX_NODE_NAME=emqx@wbroker03.domain.org"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@wbroker01.domain.org,emqx@wbroker02.domain.org]"
      - "EMQX_NODE__COOKIE=chooseacomplexpassword"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    network_mode: host
    restart: always
    volumes:
      - /home/gb/emqx:/opt/emqx/data
