---

- hosts: antiloop
  become: yes
  become_method: sudo
  tasks:
  - name: Check directory exists
    stat:
      path: /home/gb/compose/{{ wis2node }}
    register: dir_to_delete

  - name: Remove old container
    community.docker.docker_compose:
      project_src: /home/gb/compose/{{ wis2node }}
      state: absent
    when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir

  - name: Purge if exists
    file:
      state: absent
      path: /home/gb/compose/{{ wis2node }}
    when: dir_to_delete.stat.exists and dir_to_delete.stat.isdir


- hosts: manage
  become: yes
  become_method: sudo
  tasks:
  - name: Update prometheus config
    ansible.builtin.copy:
      src: /home/ansadm/data/mqtt.json
      dest: /home/gb/prometheus/mqtt.json
      owner: gb
      group: docker
      mode: '0644'
      backup: yes

  - name: Check if dynamic traefik file exists 
    stat:
      path: /home/gb/traefik/dynamic/{{ wis2node }}.yml
    register: file_to_delete

  - name: Purge if exists
    file:
      state: absent
      path: /home/gb/traefik/dynamic/{{ wis2node }}.yml
    when: file_to_delete.stat.exists
