---
- hosts: antiloop
  become: yes
  become_method: sudo
  serial: 1
  tasks:
  - name: Get infos on container
    community.docker.docker_container_info:
      name: "{{ wis2node }}" 
    register: result

  - name: Does container exist?
    community.docker.docker_compose:
      project_src: /home/gb/compose/{{ wis2node }}
      state: absent
    when: result.exists

  - name: Purge if exists
    file:
      state: absent
      path: /home/gb/compose/{{ wis2node }}
    when: result.exists

  - name: Create directory
    file:
      path: /home/gb/compose/{{ wis2node }}
      owner: gb
      group: docker
      mode: '0755'
      state: directory
    when: result.exists

  - name: Copy host env file
    ansible.builtin.copy:
      src: /home/ansadm/data/globalenv/{{ inventory_hostname_short }}.env
      dest: /home/gb/compose/{{ wis2node }}/host.env
      owner: gb
      group: docker
      mode: '0644'
      backup: no
    when: result.exists

  - name: Copy required files
    ansible.builtin.copy:
      src: /home/ansadm/data/wis2node/{{ wis2node }}/compose/
      dest: /home/gb/compose/{{ wis2node }}
      owner: gb
      group: docker
      mode: '0644'
      backup: no
    when: result.exists

  - name: Deploy new container
    community.docker.docker_compose:
      project_src: /home/gb/compose/{{ wis2node }}
      state: present
    when: result.exists

  - name: pause for 1 minute (so that new container runs)
    pause:
      seconds: 60
