= Managing WIS2 Node subscriptions
:toc: macro
:sectnums: all
:version: 0.2
:author: David Podeur
:email: david.podeur@meteo.fr
:revnumber: 0.2
:revdate: 28.02.2024 

<<<

toc::[]

<<<

The documentation _Managing WIS2 Node_ details how to manage subscriptions to WIS2 Nodes on a WIS2 Global Broker using the solution presented in _Deploying a WIS2 Global Broker_. It is based on using a docker image available on docker hub `golfvert/wis2gb`. This docker image implement the required features of the Global Broker setup, typically, the _antiloop_ feature, updating metrics,...

== Software components

On a WIS2 Global Broker, and for each WIS2 Node, one docker container is created on two of the three waloop0x hosts for redundancy purposes:

* both containers subscribe and receive messages from the remote WIS2 Node 
* only the "primary" container will process the messages and publish the relevant messages to the WIS2 Global Broker
* the "secondary" container will monitor the "primary" container and will take over in case of "primary" outage

== WIS2 Node subscription configuration

This step is used to create the container configuration.

A configuration file is needed for the each WIS2 Node:

Configuration file example:
```
gbb@wmanage:~$ cat /home/ansadm/data/env/ca-eccc-msc.env
MQTT_SUB_BROKER=mqtts://hpfx.collab.science.gc.ca
MQTT_SUB_USERNAME=******
MQTT_SUB_PASSWORD=******
MQTT_SUB_TOPIC=origin/a/wis2/ca-eccc-msc/#
MQTT_SUB_VERIFYCERT=false
CENTRE_ID=ca-eccc-msc
MQTT_MONIT_TOPIC=monitor
MSG_CHECK_OPTION=verify
TOPIC_CHECK_OPTION=verify
GDC_URL=https://api.weather.gc.ca/collections/wis2-discovery-metadata/items?lang=en&f=json&q=
```

[cols="1,1"]
|===
| *Allowed keys*
| *Descriptions* 
| MQTT_SUB_BROKER=Broker_URL
| WIS2Node URL broker such as mqtts://broker.example.com:8883 or wss://broker.example.com:443
| MQTT_SUB_USERNAME=
|
| MQTT_SUB_PASSWORD=
|
| MQTT_SUB_TOPIC=Topic_to_sub
| e.g. origin/a/wis2/fr-meteofrance/# It is suggested to subscribe to `origin/a/wis2/_centre-id_/#` so that all notifications messages from that particular centre-id can be received. It must be noted that subscription to Global Caches should be `cache/a/wis2/#` and to Global Brokers `origin/a/wis2/#,cache/a/wis2/#`
| MQTT_SUB_VERIFYCERT= true
| if using SSL should the certificate by checked (prevent self-signed certificates to work. Or not)
| MSG_CHECK_OPTION=verify
| Should messages be `verify` (just add _comment in the notification message if the message is malformed), `discard` (discard the message if not correct), `ignore` (don't check the messages). At time of writing (Feb.24) it is strongly suggested to use `ignore`
| TOPIC_CHECK_OPTION=verify
| Should topic of publication be verified against the metadata published by centre-id. The list is obtained by querying the Global Discovery Catalog.
Query is made every 15 minutes.
| GDC_URL= 
| How to query the GDC ? centre-id is added at the end of the URL.
| CENTRE_ID=
| Name_of_Center used as label
|===

See https://github.com/golfvert/WIS2-GlobalBroker-Redundancy 

The above github repository hosts the source code used by the `golfvert/wis2db` container image.

Adding a new WIS2 Node on the Global Broker, starts by creating a file call *centre-id.env* in `/home/ansadm/data/env/`. The *centre-id* is the name that the WIS Centre and WMO Secretariat have decided to use for running a WIS2 Node in that Centre.
This name is unique and will be used as an identifier throughout WIS2. 

== Add WIS2 Node subscription

The configuration file  need to be parsed in order to create all resources to deploy and start an instance of the `golfvert/wis2db` container on the waloop0x nodes. By default, one container will be deployed on two waloopx hosts.

Login as ansadm:
```
ansadm@wmanage:~$ pwd
/home/ansadm
```

After having created the file `/home/ansadm/data/env/centre-id.env` this file is parsed to create the entire configuration for this additional WIS2 Node subscription: 

Example: create all configuration files for the WIS2 Node *zm-zmd*:
```
ansadm@wmanage:~$ ./add_wis2node.sh zm-zmd
```
*add_wis2node.sh* is not verbose, but it will generate files needed to create the full configuration, including docker setup and files required for the management of the WIS2 Node subscription.

Here is an example of a content generated by *add_wis2node.sh*:

```
/home/ansadm/data/wis2node/zm-zmd/compose
/home/ansadm/data/wis2node/zm-zmd/zm-zmd_waloop.yml
/home/ansadm/data/wis2node/zm-zmd/zm-zmd_wmanage.yml
/home/ansadm/data/wis2node/zm-zmd/compose/docker-compose.yml
/home/ansadm/data/wis2node/zm-zmd/compose/globalbroker.env
/home/ansadm/data/wis2node/zm-zmd/compose/redis.env
/home/ansadm/data/wis2node/zm-zmd/compose/zm-zmd.env
```

It is then possible to deploy the WIS2 Node containers with *deploy-wis2node.yml* which will:

* randomly select two wloop0x VMs to run the containers (one for primary, the other for secondary)
* perform cleanup to make sure old containers for the same WIS2 Node do not run on the other nodes

Execution example:
```
ansadm@wmanage:~$ ansible-playbook deploy-wis2node.yml -e "wis2node=zm-zmd"

PLAY [localhost] *********************************************************************************************************************************************

TASK [Select which antiloop hosts] ***************************************************************************************************************************
changed: [localhost] => (item=waloop03)
changed: [localhost] => (item=waloop02)

PLAY [antiloop] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [waloop03]
ok: [waloop02]
ok: [waloop01]

TASK [Check directory exists] ********************************************************************************************************************************
ok: [waloop01]
ok: [waloop02]
ok: [waloop03]

TASK [Remove old container] **********************************************************************************************************************************
skipping: [waloop01]
changed: [waloop03]
changed: [waloop02]

TASK [Purge if exists] ***************************************************************************************************************************************
skipping: [waloop01]
changed: [waloop02]
changed: [waloop03]

PLAY [select] ************************************************************************************************************************************************

TASK [Add traefik config] ************************************************************************************************************************************
ok: [waloop02]
ok: [waloop03]

TASK [Create directory] **************************************************************************************************************************************
changed: [waloop03]
changed: [waloop02]

TASK [Copy host env file] ************************************************************************************************************************************
changed: [waloop02]
changed: [waloop03]

TASK [Copy required files] ***********************************************************************************************************************************
changed: [waloop02]
changed: [waloop03]

TASK [Deploy new container] **********************************************************************************************************************************
changed: [waloop03]
changed: [waloop02]

PLAY [manage] ************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Update prometheus config] ******************************************************************************************************************************
ok: [localhost]

TASK [Update traefik config] *********************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop01                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop02                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop03                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

ansadm@wmanage:~$
```

== Delete a WIS2 Node subscription

In order to remove the containers corresponding to one WIS2 Node subscription from the waloop0x nodes:

```
ansadm@wmanage:~$ ansible-playbook delete-wis2node.yml -e "wis2node=zm-zmd"

PLAY [antiloop] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [waloop03]
ok: [waloop02]
ok: [waloop01]

TASK [Check directory exists] ********************************************************************************************************************************
ok: [waloop02]
ok: [waloop01]
ok: [waloop03]

TASK [Remove old container] **********************************************************************************************************************************
skipping: [waloop01]
skipping: [waloop02]
skipping: [waloop03]

TASK [Purge if exists] ***************************************************************************************************************************************
skipping: [waloop01]
skipping: [waloop02]
skipping: [waloop03]

PLAY [manage] ************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Update prometheus config] ******************************************************************************************************************************
ok: [localhost]

TASK [Check if dynamic traefik file exists] ******************************************************************************************************************
ok: [localhost]

TASK [Purge if exists] ***************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop01                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop02                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop03                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
```

== Upgrade a WIS2 Node

Using *update-wis2node.yml*

IMPORTANT: You need to run *./add_wis2node.sh* everytime you modify your **.env* files.

The script *update-wis2node.yml* will process each waloop0x, one after the other and:

- update only the waloop0x nodes running the container
- restart the containers after update
- wait 60 seconds in order to make sure the container has started before updates next waloop0x node.


```
ansadm@wmanage:~$ vim data/env/zm-zmd.env
ansadm@wmanage:~$ ./add_wis2node.sh zm-zmd
ansadm@wmanage:~$ ansible-playbook update-wis2node.yml  -e "wis2node=zm-zmd"

PLAY [antiloop] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************
ok: [waloop01]

TASK [Get infos on container] ******************************************************************************
ok: [waloop01]

TASK [Does container exist?] *******************************************************************************
changed: [waloop01]

TASK [Purge if exists] *************************************************************************************
changed: [waloop01]

TASK [Create directory] ************************************************************************************
changed: [waloop01]

TASK [Copy host env file] **********************************************************************************
changed: [waloop01]

TASK [Copy required files] *********************************************************************************
changed: [waloop01]

TASK [Deploy new container] ********************************************************************************
changed: [waloop01]

TASK [pause for 1 minute (so that new container runs)] *****************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
Press 'C' to continue the play or 'A' to abort
ok: [waloop01]

PLAY [antiloop] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************
ok: [waloop02]

TASK [Get infos on container] ******************************************************************************
ok: [waloop02]

TASK [Does container exist?] *******************************************************************************
changed: [waloop02]

TASK [Purge if exists] *************************************************************************************
changed: [waloop02]

TASK [Create directory] ************************************************************************************
changed: [waloop02]

TASK [Copy host env file] **********************************************************************************
changed: [waloop02]

TASK [Copy required files] *********************************************************************************
changed: [waloop02]

TASK [Deploy new container] ********************************************************************************
changed: [waloop02]

TASK [pause for 1 minute (so that new container runs)] *****************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
Press 'C' to continue the play or 'A' to abort
ok: [waloop02]

PLAY [antiloop] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************
ok: [waloop03]

TASK [Get infos on container] ******************************************************************************
ok: [waloop03]

TASK [Does container exist?] *******************************************************************************
skipping: [waloop03]

TASK [Purge if exists] *************************************************************************************
skipping: [waloop03]

TASK [Create directory] ************************************************************************************
skipping: [waloop03]

TASK [Copy host env file] **********************************************************************************
skipping: [waloop03]

TASK [Copy required files] *********************************************************************************
skipping: [waloop03]

TASK [Deploy new container] ********************************************************************************
skipping: [waloop03]

TASK [pause for 1 minute (so that new container runs)] *****************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
Press 'C' to continue the play or 'A' to abort
ok: [waloop03]

PLAY RECAP *************************************************************************************************
waloop01                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop02                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop03                   : ok=3    changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
```


== Handle container version

The default container name and version is defined under:
```
ansadm@wmanage:~$ cat /home/ansadm/data/wis2node-container-tag.txt
golfvert/wis2gb:2.0.5
```

IMPORTANT: This file will need to be updated whenever newer versions of the image are released (and successfully tested).

As WIS Nodes subscriptions are added one by one, it is likely that different container versions will be used. For example, at the time of writing (Feb 24), version 2.0.4 and 2.0.5 are in use.

In order to idenfity all version used, you can use *get-container-tag.sh*:

```
ansadm@wmanage:~$ ./get-container-tag.sh
./wis2node/ca-eccc-msc/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
./wis2node/fr-meteofrance-global-broker/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
./wis2node/de-dwd-gts-to-wis2/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
./wis2node/fr-meteofrance/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
./wis2node/zm-zmd/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
./wis2node/cu-insmet/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
./wis2node/bz-nms/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
./wis2node/it-meteoam/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
./wis2node/cn-cma-global-broker/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.5
```

You can also focus on a specific version:
```
ansadm@wmanage:~$ ./get-container-tag.sh   golfvert/wis2gb:2.0.4
./wis2node/fr-meteofrance-global-broker/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
./wis2node/de-dwd-gts-to-wis2/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
./wis2node/fr-meteofrance/compose/docker-compose.yml:      image: golfvert/wis2gb:2.0.4
```

In oder to upgrade (or downgrade) to the image version specified under `/home/ansadm/data/wis2node-container-tag.txt`, the *upgrade-container-tag.s* will generate the shell commands needed to perform the upgrade:

```
ansadm@wmanage:~$ ./upgrade-container-tag.sh golfvert/wis2gb:2.0.4
./add_wis2node.sh fr-meteofrance-global-broker
ansible-playbook update-wis2node.yml -e wis2node=fr-meteofrance-global-broker
./add_wis2node.sh de-dwd-gts-to-wis2
ansible-playbook update-wis2node.yml -e wis2node=de-dwd-gts-to-wis2
./add_wis2node.sh fr-meteofrance
ansible-playbook update-wis2node.yml -e wis2node=fr-meteofrance
```

You may then paste those commands manually to a terminal to perform the upgrade:

```
ansible-playbook update-wis2node.yml -e wis2node=fr-meteofrance
ansadm@wmanage:~$ ./add_wis2node.sh fr-meteofrance-global-broker
Current container tag: golfvert/wis2gb:2.0.5
ansadm@wmanage:~$ ansible-playbook update-wis2node.yml -e wis2node=fr-meteofrance-global-broker

PLAY [antiloop] **********************************************************************************************************************************************

[...]
TASK [Copy required files] ***********************************************************************************************************************************
changed: [waloop03]

TASK [Deploy new container] **********************************************************************************************************************************
changed: [waloop03]

TASK [pause for 1 minute (so that new container runs)] *******************************************************************************************************
Pausing for 60 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
Press 'C' to continue the play or 'A' to abort
ok: [waloop03]

PLAY RECAP ***************************************************************************************************************************************************
waloop01                   : ok=3    changed=0    unreachable=0    failed=0    skipped=6    rescued=0    ignored=0
waloop02                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop03                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```