= Managing WIS2 Node
:toc: macro
:sectnums: all
:version: 0.1b
:author: David Podeur
:email: david.podeur@meteo.fr
:revnumber: 0.1
:revdate: 27.02.2024 

<<<

toc::[]

<<<

The documentation _Managing WIS2 Node_ details how to manage subscriptions to WIS2 Nodes on a WIS2 Global Broker.

== Software components

Each WIS2 Node is harversted by at least 2 dedicated docker containers on the WIS2 Global Broker:

* all containers receive messages from the source WIS2 Node 
* only the "primary" container will check for duplicate messages (antiloop) and feed the WIS2 Global Broker
* the "secondary" container(s) will monitor the "primary" container and will take over in case of "primary" outage

== WIS2 Node subscription configuration

In this step, the primary and secondary containers will be created.

A configuration file is needed for the given WIS2 Node:

Example:
```
gbb@wmanage:~$ cat /home/ansadm/data/env/ca-eccc-msc.env
MQTT_SUB_BROKER=mqtts://hpfx.collab.science.gc.ca
MQTT_SUB_USERNAME=******
MQTT_SUB_PASSWORD=******
MQTT_SUB_TOPIC=origin/a/wis2/ca-eccc-msc/#
MQTT_SUB_VERIFYCERT=false
CENTRE_ID=ca-eccc-msc
MQTT_MONIT_TOPIC=monitor
MSG_CHECK_OPTION=verify
TOPIC_CHECK_OPTION=verify
GDC_URL=https://api.weather.gc.ca/collections/wis2-discovery-metadata/items?lang=en&f=json&q=
```

[cols="1,1"]
|===
| *Allowed keys*
| *Descriptions* 
| MQTT_SUB_BROKER=Broker_URL
| WIS2Node URL broker such as mqtts://broker.example.com:8883 or wss://broker.example.com:443
| MQTT_SUB_USERNAME=
|
| MQTT_SUB_PASSWORD=
|
| MQTT_SUB_TOPIC=Topic_to_sub
| e.g. origin/a/wis2/fra/#. 
| MQTT_SUB_VERIFYCERT= true
| if using SSL should the certificate by checked (prevent slef-signed certificates to work. Or not)
| MQTT_PUB_BROKER=GlobalBroker_URL
| Global Broker URL such as mqtts://globalbroker.site.com:8883 or wss://globalbroker.site.com:443
| MQTT_PUB_USERNAME=
|
| MQTT_PUB_PASSWORD=
|
| MQTT_MONIT_TOPIC=
| Topic_to_publish_on_Global_Broker
| MSG_CHECK_OPTION=verify
| Should messages be "verify" (just add _comment in the notification message), "discard" (bin the message if not correct), "ignore" (don't check the messages)
| TOPIC_CHECK_OPTION=verify
| Should topic of publication be verified against the metadata published by centreid. The list is obtained by querying the Global Discovery Catalog.
Query is made every 15 minutes.
| GDC_URL= 
| How to query the GDC ? centre-id is added at the end of the URL.
| CENTRE_ID=
| Name_of_Center used as label and as a key when 2 (or more) containers are running 
| REDIS_URL=[{"host":@IP1,"port":port1},{"host":@IP2,"port":port2},......] 
| A JSON Array with all host:port instances of the redis cluster
|===

Source doc: https://github.com/golfvert/WIS2-GlobalBroker-Redundancy

== Add WIS2 Node subscription

Login as ansadm:
```
ansadm@wmanage:~$ pwd
/home/ansadm
```

Create config files for the container:
```
ansadm@wmanage:~$ ./add_wis2node.sh zm-zmd
```
There is no output to this command, but it will generate files needed to create the containers.

```
/home/ansadm/data/wis2node/zm-zmd
/home/ansadm/data/wis2node/zm-zmd/compose
/home/ansadm/data/wis2node/zm-zmd/zm-zmd_waloop.yml
/home/ansadm/data/wis2node/zm-zmd/zm-zmd_wmanage.yml
/home/ansadm/data/wis2node/zm-zmd/compose/docker-compose.yml
/home/ansadm/data/wis2node/zm-zmd/compose/globalbroker.env
/home/ansadm/data/wis2node/zm-zmd/compose/redis.env
/home/ansadm/data/wis2node/zm-zmd/compose/zm-zmd.env
```


Deploy containers:
```
ansadm@wmanage:~$ ansible-playbook deploy-wis2node.yml -e "wis2node=zm-zmd"

PLAY [localhost] *********************************************************************************************************************************************

TASK [Select which antiloop hosts] ***************************************************************************************************************************
changed: [localhost] => (item=waloop03)
changed: [localhost] => (item=waloop02)

PLAY [antiloop] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [waloop03]
ok: [waloop02]
ok: [waloop01]

TASK [Check directory exists] ********************************************************************************************************************************
ok: [waloop01]
ok: [waloop02]
ok: [waloop03]

TASK [Remove old container] **********************************************************************************************************************************
skipping: [waloop01]
changed: [waloop03]
changed: [waloop02]

TASK [Purge if exists] ***************************************************************************************************************************************
skipping: [waloop01]
changed: [waloop02]
changed: [waloop03]

PLAY [select] ************************************************************************************************************************************************

TASK [Add traefik config] ************************************************************************************************************************************
ok: [waloop02]
ok: [waloop03]

TASK [Create directory] **************************************************************************************************************************************
changed: [waloop03]
changed: [waloop02]

TASK [Copy host env file] ************************************************************************************************************************************
changed: [waloop02]
changed: [waloop03]

TASK [Copy required files] ***********************************************************************************************************************************
changed: [waloop02]
changed: [waloop03]

TASK [Deploy new container] **********************************************************************************************************************************
changed: [waloop03]
changed: [waloop02]

PLAY [manage] ************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Update prometheus config] ******************************************************************************************************************************
ok: [localhost]

TASK [Update traefik config] *********************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop01                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop02                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop03                   : ok=9    changed=6    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

ansadm@wmanage:~$
```

The playbook will:
- find 2 suitable wloop0x nodes (one for primary, the other for secondary)


== Delete a WIS2 Node

In order to remove the containers from the waloop0x nodes:

```
ansadm@wmanage:~$ ansible-playbook delete-wis2node.yml -e "wis2node=zm-zmd"



PLAY [antiloop] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [waloop03]
ok: [waloop02]
ok: [waloop01]

TASK [Check directory exists] ********************************************************************************************************************************
ok: [waloop02]
ok: [waloop01]
ok: [waloop03]

TASK [Remove old container] **********************************************************************************************************************************
skipping: [waloop01]
skipping: [waloop02]
skipping: [waloop03]

TASK [Purge if exists] ***************************************************************************************************************************************
skipping: [waloop01]
skipping: [waloop02]
skipping: [waloop03]

PLAY [manage] ************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Update prometheus config] ******************************************************************************************************************************
ok: [localhost]

TASK [Check if dynamic traefik file exists] ******************************************************************************************************************
ok: [localhost]

TASK [Purge if exists] ***************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
waloop01                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop02                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
waloop03                   : ok=2    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
```



== Upgrade a WIS2 Node
Be careful when upgrading from container 1.x to 2.x.